# Travis CI build pipeline
# --------------------------------------------

language: csharp
solution: ExceptionLib.sln
mono: none
dotnet: 3.1.301

addons:
  apt:
    packages:
      - zip
      - tar
      - gzip

before_script:
  - set -e
  - dotnet restore

script:
  - |
    if [ -z "$TRAVIS_TAG" ]
    then
      set -e
      dotnet build -c Release
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" 
      bash <(curl -s https://codecov.io/bash) -Z
    fi

before_deploy:
  - set -e
  - dotnet build -c Release -o ./output
  - zip ./Exception.zip ./output/RaGae.BaseExceptionLib.dll ./output/RaGae.BaseExceptionLib.pdb ./output/RaGae.BaseExceptionLib.deps.json
  - tar cfvz ./Exception.tar.gz ./output/RaGae.BaseExceptionLib.dll ./output/RaGae.BaseExceptionLib.pdb ./output/RaGae.BaseExceptionLib.deps.json

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - "./Exception.zip"
    - "./Exception.tar.gz"
    - "./output/RaGae.BaseExceptionLib.dll"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - dotnet nuget push ./output/RaGae.Exception.*.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json